server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mydatabase"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
  session:
    timeout: 30m